/* ============================================
   MILTHA — Word by Word Data
   Key passages across all 27 NT books
   ============================================ */

const WBW_DATA = {
  ara: {
    ref: 'JOHN 1:1 · PESHITTA · ARAMAIC — THE LANGUAGE OF JESUS',
    rtl: false,
    verse: '"In the beginning was the Word, and the Word was with God, and the Word was God."',
    words: [
      {orig:'ܒ݁ܪܺܫܺܝܬ݂',translit:"B'reshith",gloss:'IN THE\nBEGINNING',pos:'Prepositional Phrase',root:'ܪܺܫ (resh) — head, first',literal:'In the head / At the first',english:'In the beginning',meaning:"The same opening as Genesis 1:1 in Aramaic. By opening with this word, John deliberately echoes the creation narrative. The Word who was present at creation is now being revealed in flesh. The Peshitta reader would have heard this as Genesis all over again.",strongs:"SYRIAC LEXICON · cf. GENESIS 1:1 LXX ἐν ἀρχῇ · PESHITTA GENESIS ܒ݁ܪܺܫܺܝܬ݂",xrefs:[{ref:'GENESIS 1:1',text:'"In the beginning God created the heavens and the earth."'},{ref:'PROVERBS 8:22',text:'"The LORD possessed me at the beginning of his work, the first of his acts of old."'},{ref:'JOHN 17:5',text:'"And now, Father, glorify me in your own presence with the glory that I had with you before the world existed."'}]},
      {orig:'ܐܺܝܬ݂ܰܘܗ݈ܝ',translit:'ithawhy',gloss:'WAS /\nEXISTED',pos:'Verb — Existential',root:'ܐܺܝܬ (ith) — being, existence',literal:'He was / He existed (eternally)',english:'was',meaning:"Carries the sense of eternal, continuous existence — not 'came to be' but 'was already existing.' The same distinction Jesus makes in John 8:58 — 'Before Abraham was (hwa — came to be), I AM (ithay — eternally exist).' This verb is the key to understanding Christ's pre-existence.",strongs:"SYRIAC ROOT: ܐܺܝܬ · cf. GREEK ἦν (ēn) — imperfect of εἰμί · STRONG'S G2258",xrefs:[{ref:'JOHN 8:58',text:'"Before Abraham was, I AM."'},{ref:'EXODUS 3:14',text:'"I AM WHO I AM. Say this to the people of Israel: I AM has sent me to you."'},{ref:'MICAH 5:2',text:'"Whose goings forth are from of old, from everlasting."'}]},
      {orig:'ܡܶܠܬ݂ܳܐ',translit:'Miltha',gloss:'THE\nWORD',pos:'Noun — Emphatic State',root:'ܡܠܐ (mla) — to fill, to speak forth, to utter',literal:'The Word / The Divine Utterance / The One who speaks forth',english:'the Word',meaning:"MILTHA — the platform's name, taken from this exact word. In Aramaic thought, the Word of God is not merely speech but the creative, divine utterance that brings reality into existence. It is personal, active, and eternal. This is the name John chose for the pre-incarnate Christ in the language Christ Himself spoke every day.",strongs:"SYRIAC: ܡܶܠܬ݂ܳܐ · cf. GREEK Λόγος (Logos) · HEBREW דָּבָר (Dabar) · JOHN 1:1 PESHITTA",xrefs:[{ref:'REVELATION 19:13',text:'"He is clothed in a robe dipped in blood, and the name by which he is called is The Word of God."'},{ref:'PSALM 33:6',text:'"By the word of the LORD the heavens were made, and by the breath of his mouth all their host."'},{ref:'1 JOHN 1:1',text:'"That which was from the beginning, which we have heard, which we have seen with our eyes, which we looked upon and have touched with our hands, concerning the word of life."'}]},
      {orig:'ܠܘܳܬ݂',translit:'lwath',gloss:'WITH /\nBESIDE',pos:'Preposition',root:'ܠܘܬ (lwath) — toward, in the presence of, face-to-face',literal:'Face-to-face with / Alongside / In direct communion with',english:'with',meaning:"Far richer than the English 'with.' Carries the sense of intimate proximity and face-to-face presence. The Word was not merely in the same place as God — He was in direct, personal, active relationship with God. The Greek equivalent πρός (pros) carries the same directional, relational force.",strongs:"cf. GREEK πρός (pros) — toward, face-to-face · STRONG'S G4314",xrefs:[{ref:'JOHN 17:24',text:'"Father, I desire that they also, whom you have given me, may be with me where I am, to see my glory."'},{ref:'JOHN 17:5',text:'"The glory that I had with you before the world existed."'}]},
      {orig:'ܐܰܠܳܗܳܐ',translit:'Alaha',gloss:'GOD',pos:'Noun — Divine Name, Emphatic State',root:'ܐܠ (el) — power, might, the divine',literal:'God / The Mighty One / The All-Powerful',english:'God',meaning:"ALAHA — the Aramaic name for God used by Jesus Himself. In Gethsemane He cried 'Abba, Alaha' (Mark 14:36 in Aramaic). From the cross He cried 'Eli, Eli, lama sabachthani' — using the related Aramaic word. This is God in the language of Christ's daily speech, His prayers, and His teaching.",strongs:"SYRIAC: ܐܰܠܳܗܳܐ · cf. HEBREW אֱלֹהִים (Elohim) · ARABIC الله (Allah) · STRONG'S H430",xrefs:[{ref:'MARK 14:36',text:'"Abba, Father, all things are possible for you. Remove this cup from me."'},{ref:'MARK 15:34',text:'"Eloi, Eloi, lema sabachthani? — My God, my God, why have you forsaken me?"'},{ref:'JOHN 10:30',text:'"I and the Father are one."'}]},
      {orig:'ܗܽܘ',translit:'hu',gloss:'HE /\nHIMSELF',pos:'Personal Pronoun — Emphatic',root:'ܗܘ (hu) — he, this one',literal:'He himself / That very one',english:'God (he was)',meaning:"The emphatic pronoun placed after the predicate — 'and God was He, the Word.' The Aramaic construction mirrors the Greek θεὸς ἦν ὁ Λόγος exactly. The placement is a theological statement: the Word does not merely participate in divinity — He is the divine.",strongs:"SYRIAC: ܗܽܘ · cf. GREEK αὐτός",xrefs:[{ref:'JOHN 10:38',text:'"The Father is in me and I am in the Father."'},{ref:'COLOSSIANS 2:9',text:'"For in him the whole fullness of deity dwells bodily."'}]}
    ]
  },
  gk: {
    ref: 'JOHN 1:1 · TEXTUS RECEPTUS · GREEK',
    rtl: false,
    verse: '"In the beginning was the Word, and the Word was with God, and the Word was God."',
    words: [
      {orig:'Ἐν',translit:'En',gloss:'IN',pos:'Preposition',root:'ἐν — in, within, among',literal:'In / Within',english:'In',meaning:"A preposition of location. Locates the Word within the primordial beginning itself — not outside it. The Word is not described as existing before the beginning and then entering it; He is present within it from the very start.",strongs:"STRONG'S G1722 · ἐν",xrefs:[]},
      {orig:'ἀρχῇ',translit:'archē',gloss:'BEGINNING /\nORIGIN',pos:'Noun — Dative Feminine Singular',root:'ἀρχή — beginning, origin, first cause, ruling power',literal:'The beginning / The origin / The first principle',english:'the beginning',meaning:"ARCHE carries far more than a chronological start. It means the origin, the first principle, the ruling source from which all else proceeds — the very ground of existence. Jesus used this of Himself in Revelation 22:13: 'I am...the Beginning and the End.' He is not merely first in time; He is the source of all that exists.",strongs:"STRONG'S G746 · ἀρχή · cf. REVELATION 1:8, 22:13",xrefs:[{ref:'REVELATION 22:13',text:'"I am the Alpha and the Omega, the first and the last, the beginning and the end."'},{ref:'COLOSSIANS 1:18',text:'"He is the beginning, the firstborn from the dead, that in everything he might be preeminent."'}]},
      {orig:'Λόγος',translit:'Logos',gloss:'WORD /\nREASON',pos:'Noun — Nominative Masculine Singular',root:'λέγω (legō) — to speak, to reason, to gather, to lay in order',literal:'The Word / The Reason / The Logic / The One who gathers all things together',english:'Word',meaning:"LOGOS — one of the most profound words in Greek philosophy and theology. To Greek thinkers: the rational principle governing the cosmos. To Jewish readers familiar with the Targums: the divine Word (Memra) by which God created. To the Aramaic reader: MILTHA. John declares this eternal Logos became flesh. He is not an idea or a principle — He is a person.",strongs:"STRONG'S G3056 · Λόγος · cf. ARAMAIC ܡܶܠܬ݂ܳܐ (Miltha) · HEBREW דָּבָר (Dabar)",xrefs:[{ref:'HEBREWS 1:1-2',text:'"In these last days he has spoken to us by his Son, whom he appointed the heir of all things, through whom also he created the world."'},{ref:'1 JOHN 1:1',text:'"That which was from the beginning, which we have heard, which we have seen with our eyes."'}]},
      {orig:'πρὸς',translit:'pros',gloss:'WITH /\nTOWARD',pos:'Preposition + Accusative',root:'πρός — toward, in the direction of, face-to-face, in relation to',literal:'Face-to-face with / In direct relationship with / Turned toward',english:'with',meaning:"PROS is directional and relational — it means facing toward, in active communion. The Logos was not merely alongside God; He was in eternal, active, face-to-face relationship with God. The Greek preposition chosen by John (not the simpler μετά or σύν) specifically conveys this intimacy and direct personal encounter.",strongs:"STRONG'S G4314 · πρός · cf. ARAMAIC ܠܘܳܬ݂ (lwath)",xrefs:[]},
      {orig:'Θεὸς',translit:'Theos',gloss:'GOD\n(NATURE)',pos:'Noun — Predicate Nominative (anarthrous — no article)',root:'Θεός — God, the divine being, divine nature',literal:'God in nature / Divine in essence',english:'God',meaning:"The most theologically debated word in this verse. Theos here has NO definite article — this is critical. In Greek, the definite article identifies a specific person ('the God,' i.e., the Father). Without it, the word emphasizes divine nature or quality. Colwell's Rule (1933) confirms: when a predicate noun precedes the verb and is anarthrous, it indicates quality. The Word is not 'a god' — He is fully divine in nature. Early fathers including Ignatius used this verse to affirm Christ's full deity.",strongs:"STRONG'S G2316 · Θεός · cf. COLWELL'S RULE · JOHN 10:30",xrefs:[{ref:'JOHN 10:30',text:'"I and the Father are one."'},{ref:'COLOSSIANS 2:9',text:'"For in him the whole fullness of deity dwells bodily."'},{ref:'PHILIPPIANS 2:6',text:'"Who, though he was in the form of God, did not count equality with God a thing to be grasped."'}]}
    ]
  },
  heb: {
    ref: 'JOHN 1:1 · HEBREW NEW TESTAMENT · DELITZSCH 1877',
    rtl: true,
    verse: '"In the beginning was the Word, and the Word was with God, and the Word was God."',
    words: [
      {orig:'בְּרֵאשִׁית',translit:"B'reishit",gloss:'IN THE\nBEGINNING',pos:'Prepositional Phrase',root:'רֹאשׁ (rosh) — head, beginning, first',literal:'In the head / At the beginning',english:'In the beginning',meaning:"The same opening word as the entire Hebrew Bible — Genesis 1:1 begins 'B\'reishit bara Elohim.' John's deliberate echo: the one through whom God creates in Genesis 1 is the same one described in John 1. The Word is not a new addition to the story — He is its beginning.",strongs:"STRONG'S H7225 · רֵאשִׁית · GENESIS 1:1 · JOHN 1:1 (Delitzsch)",xrefs:[{ref:'GENESIS 1:1',text:'"In the beginning, God created the heavens and the earth."'},{ref:'PROVERBS 8:22-23',text:'"The LORD possessed me at the beginning of his work, the first of his acts of old. Ages ago I was set up, at the first, before the beginning of the earth."'}]},
      {orig:'הַדָּבָר',translit:'ha-Dabar',gloss:'THE\nWORD',pos:'Noun — Definite with Article',root:'דָּבַר (davar) — to speak, to arrange, to lead forward',literal:'The Word / The Thing Spoken / The Matter Arranged',english:'the Word',meaning:"DABAR is the Hebrew equivalent of Logos and Miltha. Throughout the Old Testament, 'the Word of the LORD' (Devar YHWH) is a divine agent — it creates (Genesis 1), commands, judges, and saves. Isaiah 55:11: 'My word that goes out from my mouth shall not return to me empty.' Psalm 107:20: 'He sent out his word and healed them.' John reveals: that Word is a person with a name.",strongs:"STRONG'S H1697 · דָּבָר · cf. PSALM 33:6, 107:20 · ISAIAH 55:11",xrefs:[{ref:'PSALM 107:20',text:'"He sent out his word and healed them, and delivered them from their destruction."'},{ref:'ISAIAH 55:11',text:'"So shall my word be that goes out from my mouth; it shall not return to me empty."'},{ref:'PSALM 33:6',text:'"By the word of the LORD the heavens were made."'}]},
      {orig:'הָאֱלֹהִים',translit:'ha-Elohim',gloss:'GOD\n(THE)',pos:'Noun — Definite, Plural of Majesty',root:'אֵל (El) — God, power, might',literal:'The God / The Mighty Ones (plural of majesty)',english:'God',meaning:"ELOHIM is grammatically plural — a 'plural of majesty' indicating infinite greatness. This plurality has sparked theological reflection from the earliest rabbis. Genesis 1:26 uses Elohim with a plural verb: 'Let us make man in our image.' The Dabar being with Elohim is not an addition to the divine but participation within it — within the same infinite being who spoke creation into existence.",strongs:"STRONG'S H430 · אֱלֹהִים · cf. GENESIS 1:1, 1:26 · DEUTERONOMY 6:4",xrefs:[{ref:'GENESIS 1:26',text:'"Then God said, \'Let us make man in our image, after our likeness.\'"'},{ref:'DEUTERONOMY 6:4',text:'"Hear, O Israel: The LORD our God, the LORD is one."'}]}
    ]
  }
};
